name: Test Checkout With Branch Name
on: [ pull_request ]

jobs: 
  test-checkout:
    runs-on: ubuntu-latest
    steps: 
      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo ${GITHUB_REF#refs/heads/}
        id: extract_branch

      - uses: actions/checkout@v3
        with: 
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Commit / Push 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "ci: updated image tag to ${{ steps.increment.outputs.newVers }}"
          git push
