name: Test Checkout With Branch Name
on: [ pull_request ]

jobs: 
  test-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6
      
      - uses: actions/checkout@v3
        with: 
          ref: "${{ steps.branch-name.outputs.current_branch }}"

      - name: Commit / Push 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "ci: updated image tag to ${{ steps.increment.outputs.newVers }}"
          git push
